management.context-path: /manage
management.security.enabled: true

jolokia.config.mimeType: application/json

endpoint.jolokia.sensitive: true

security.user.name: lars
security.user.password: beuster
security.basic.enabled: true

server.port: 8080
my:
  override: application.properties
  def: application.properties
  features:
    feature1: FEATURE1

---

spring:
    profiles: test

my:
  override: application-test.properties
