# used by the client to register at the server
spring.boot.admin:
    username: admin
    password: ipool2015
    period: 10000000

management:
    security.enabled: true
    security.role: admin

security:
    user.name: admin
    user.password: ipool2015

endpoints:
    jolokia.sensitive: true

zuul.sensitiveHeaders : Cookie

